// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SimpleTest

//#include "../ui.h"
#include "ui.h"
#include <Streaming.h>

#ifndef BLOG
  #define BLOG          millis()    //Used in logging
#endif

void ui_Screen1_screen_init(void)
{
  Serial << BLOG << " ui_Screen1_screen_init(): Call ui_Screen1= lv_obj_create(NULL)" << endl;
  ui_Screen1= lv_obj_create(NULL);
  lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

  Serial << BLOG << " ui_Screen1_screen_init(): Call ui_Label1= lv_label_create(ui_Screen1)" << endl;
  ui_Label1= lv_label_create(ui_Screen1);
  lv_obj_set_width    (ui_Label1, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height   (ui_Label1, LV_SIZE_CONTENT);    /// 1
  lv_obj_set_x        (ui_Label1, 52);
  lv_obj_set_y        (ui_Label1, 37);
  lv_obj_set_align    (ui_Label1, LV_ALIGN_CENTER);
  lv_label_set_text   (ui_Label1, "Plain old text");
/*
  lv_label_set_text(ui_Label1, "Montserrat 48 Text");
  lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
*/
/*
  lv_label_set_text   (ui_Label1, "Montserrat 16 Text");
  lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
*/

  Serial << BLOG << " ui_Screen1_screen_init(): Call ui_Image1= lv_img_create(ui_Screen1)" << endl;
  ui_Image1= lv_img_create(ui_Screen1);
  lv_img_set_src      (ui_Image1, &ui_img_boise011624_png);
  lv_obj_set_width    (ui_Image1, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height   (ui_Image1, LV_SIZE_CONTENT);    /// 1
  lv_obj_set_x        (ui_Image1, -236);
  lv_obj_set_y        (ui_Image1, -73);
  lv_obj_set_align    (ui_Image1, LV_ALIGN_CENTER);
  lv_obj_add_flag     (ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
  lv_obj_clear_flag   (ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
  lv_img_set_zoom     (ui_Image1, 100);

  lv_timer_handler(); /* let the GUI do its work */
  Serial << BLOG << " ui_Screen1_screen_init(): Done." << endl;
  return;
} //ui_Screen1_screen_init
