// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Thermostat_022024C

#include "ui.h"

void fan_speed_value(lv_event_t * e)
{
	// Your code here
}
