// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ThermoArduino

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Just_a_Test = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Just_a_Test, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Just_a_Test, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Just_a_Test, -3);
    lv_obj_set_y(ui_Just_a_Test, -161);
    lv_obj_set_align(ui_Just_a_Test, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Just_a_Test, "Testing 2/21/24a");
    lv_obj_set_style_text_font(ui_Just_a_Test, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

}
